### ISSUE TITLE
Camera is still being used by Matrix video chat despite me not being in a call.

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-call#232]
**Describe the bug**
My camera is still being used by Matrix video chat despite me not being in a call.
The home page of Matrix Video Chat is clearly out of a call, but (as per screenshots):
- the light of my camera is on (Screenshot 2)
- when focused on another tab of FF the video chat tab icon blinks with a red camera (Screenshot 1)
- my mac clearly says that it's Matrix Video Chat using the camera (Screenshot 2)

Using Firefox on mac Big Sur. Unsure how to rageshake

**To Reproduce**
Last things I did until I noticed the issue:
1. I had a call with Matrix Video Chat last night, using an USB camera
2. I left the conference, unplugged the USB camera and set my mac to sleep
3. I've had a couple of Jitsi conferences without issue this  morning (using the Mac camera)
4. I just had a Zoom call too
5. I only noticed now that the camera is still being used
6. If I join a Jitsi call and click on the camera icon in the status bar of my Mac it still says the camera is being used by Matrix Video Chat
7. Only closing the tab releases the camera

**Expected behavior**
The camera shouldn't be used by the app if I'm not in a call

**Screenshots**
Screenshot 1
<img width="374" alt="Screenshot 2022-02-23 at 12 32 01" src="https://user-images.githubusercontent.com/8582858/155321418-3cae173d-fae4-439c-ad2f-ca2acdf70276.png">

Screenshot 2
![IMG_7924](https://user-images.githubusercontent.com/8582858/155321413-de954601-ab77-4c8e-8a96-c3f08b8be582.jpg)

**Desktop (please complete the following information):**
 - OS: Big Sur 11.6
 - Browser: Firefox 97.0.1

**Comment by nadonomy** [comment]
I also had this this morning but failed to reproduce.

**Comment by robertlong** [comment]
Should be fixed in https://github.com/vector-im/matrix-video-chat/commit/42e2041d6f50b66f60f6423316254ad55cc5c7dc

**Comment by lampholder** [comment]
I'm definitely still seeing this on https://call.element.io as of five minutes ago.

**Comment by robertlong** [comment]
@lampholder do you have any reproduction steps? You've entered the call, you're on it for a while, and then you hit the leave room button? The light is still on when back on the home page? Can you think of anything else you might be doing?

**Comment by lampholder** [comment]
I'm on an Element Call call right now - I'll see what happens when I leave it.

**Comment by lampholder** [comment]
Yep - same experience. I clicked "Hang up" and the camera stayed active. Closing the tab doesn't release the camera - I have to go to system settings to revoke/restore camera access system wide to release the camera again.

Windows 10, Firefox Nightly

**Comment by robertlong** [comment]
> Yep - same experience. I clicked "Hang up" and the camera stayed active. Closing the tab doesn't release the camera - I have to go to system settings to revoke/restore camera access system wide to release the camera again.
> 
> Windows 10, Firefox Nightly

Oh? Closing the tab doesn't release the camera? That sounds like a big browser bug then. Can you try in non-nightly Firefox?

**Comment by michaelkaye** [comment]
I can replicate something like this easily - not when on the home page , but when on the post-call page.

I had a user on an android phone using firefox, it is setup to ask for video/audio permission each time. To replicate, I join a call with another user, was asked to grant permissions.

I then left the call via the hangup button, and was asked a second time to grant video/audio permissions when being shown the post call page (the one about creating an account).

With firefox on laptop this is also visible -  the hardware camera light stays on after ending a call and showing the post-call page.

Clicking the link "return to home screen" does terminate the camera usage correctly.

**Comment by robintown** [comment]
We've now [fixed this](https://github.com/vector-im/element-call/pull/602), and a release is going out shortly
