### ISSUE TITLE
Adding Voice Only Calls

### ISSUE THREAD

**Issue by DEVXIX** [vector-im/element-call#3354]
#### What would you like to do?
Add a button that directly, allow the user to use voice call instead of a video call on Element Apps such as Element X
#### Why would you like to do it?
Because having a separate, voice only icon, is convenient for most users who would rather do voice call only, if video call is not needed 
#### How would you like to achieve it?

Adding it to Element X would enhance the application, this was previously available on Element IOS but isn't available on Element X

### Have you considered any alternatives?

Not really

### Additional context

I currently have my own version of the previous Element IOS , I really like the work on Element X and want to migrate, so i would like to ask for audio calls on private/group calls

Adding an option for audio calls next to video calls inside the room / private chats

**Comment by Destinyg133** [comment]
IMHO UX needs redesign with proper solution to not connect to video feed by partipicants who don't want it

**Comment by bro2020** [comment]
This is also important to me.

**Comment by jackedproxy** [comment]
May be worth having the video feed off by default instead, at least until there's a better idea of what the general UX for element-call is supposed to be.

**Comment by akarl10** [comment]
> May be worth having the video feed off by default instead, at least until there's a better idea of what the general UX for element-call is supposed to be.

I think this is not enough on mobile because audio call means earpiece audio output by default whereas video means speaker output. It may be that other VoIP options change the audio output automatically, but I think the proper solution for element x would be a specific loudspeaker button like on a normal call.

**Comment by VeryShuu** [comment]
I'm really looking forward to this functionality

**Comment by azharkov78** [comment]
Me too. Need only voice call.

**Comment by SerhiiMandrykin** [comment]
Agree

**Comment by Dark-Sheepa** [comment]
Yes, please, this has not my 100%, but 1000% support. :)) It should have been created the other way around. Whether for work calls with colleagues (I don't mean screen sharing, which has its uses at work.) or for playing games with friends in the evening, pure voice is far more important than video transmission, which is more niche.

**Comment by aiboost** [comment]
I'm sorry, but why this ticket has been closed? 
The linked issue has nothing with the current one.

Unfortunately I still don't see any "Voice call" button in iOS app, and my headset is not active by default in prior to speaker phone. This means the interlocutors occasionally expose their picture when they don't intend to, and also they expose the private conversation on public joining to any call, everybody can hear it.

I also vote for this feature. Thanks.

**Comment by Half-Shot** [comment]
Hey. So #3493 enables the ability for clients to signal whether they'd like to start a voice or video call. However, support across Element clients is pretty weak at the moment. https://github.com/element-hq/element-web/pull/30817 will enable support for Element Web but work for the EX platforms is in progress.

I'll re-open the issue as currently we don't have good platform support.

**Comment by Mr-DS-ML-85** [comment]
Bro, we need both audio and video calls cause Element should not be limited to organizations and teams and enthusiast, rather we should add both feature so that Family, friends can use it. Even I saw many people are agreed to use element it because it's the best alternative to Whatsapp. And I have already ditched WhatsApp for Element.
so my request is to add both audio and video calls. Because it's not limited to organizations and teams but also friends and family.

**Comment by Half-Shot** [comment]
https://github.com/element-hq/element-web/pull/30817 has since been merged so Element Web can now make voice-only calls from the room header.

Element X still needs to support the feature however.

**Comment by Sh-AhsanArif** [comment]
Any update on the expected timeline or priority for this feature for Element X? A rough estimate would be appreciated. Thanks!

**Comment by ToddCrimson** [comment]
Hi, just checking in, if there is a timeline to implement audio call button / or some way to start an audio call in mobile clients (android / ios) without first going to Video / Speakerphone, then switching to Audio / Handset.

Please help

**Comment by judicandus** [comment]
Not having a dedicated audio call button is a deal breaker to move to the new element x app. 99.9% of the time users do only voice calls. As it is now, it's a nuisance to change to audio only, especially for the elderly who don't understand what to do to disable the speaker audio when in public, causing distress to the user and embarrassement. ATM It's very difficult to suggest people move from WhatsApp to element x when a basic functionality such as audio call is counter intuitive. 
The current solution, to suggest everyone to use element classic and in the future ask everyone to move to the better (except for this lack of feature) Element X is also a nuisance. 
I'm grateful to the developers and I love matrix, but not having a default audio button is a poor choice that makes it even more difficult to convert users.

**Comment by Rain4Cats** [comment]
I would like to add that an optional "Are you sure you want to call?" confirmation is crucial.
Due to the nature of touch screen interaction, accidental actions are to be expected.

Socially speaking, the initiation of a call is an immediate request for someone's time and attention. 

It is undeniably an "interruption", someone receiving a call will have their conversation, meeting or sleep interrupted.
It also emits a ringtone noise from the recievers' device.

Generally, what I'm trying to say is that a call has "social consequences" and accidental calls have and will lead to distress or inconvenience.

Therefore, I consider it crucial to include *the option* to ask for confirmation before starting a call.

(Apologies if this is not the proper way to provide feedback as I am a total newbie on Github ♥️)

**Comment by rwjack** [comment]
Idk who is project/product managing Element X/Web, but I'd fire that person out of a cannon if I could.

Element has crazy potential to reach important enterprise clients - meanwhile the management team is out here sleeping on the job.

I also don't know how many times this needs to be said: 
Just straight up start copying discord regarding design choices - stop reinventing the wheel - the whole idea behind element/synapse/matrix is encryption, privacy and security, not making a cool looking UI.

Simplifying the design process like this, knowing what's good and making a replica of it, things will start going faster for one, and secondly Element will start to boom, but someone needs to smack their fist on the table first.

There's a shit ton of people out here giving freebie QA, meanwhile the feedback is being implemented at a rate slower than my granny's driving.

Before anyone says - "you're free to make a PR" - you should know that Element (New Vector), the company that works on Element itself, is a for-profit company, and I sure as shit ain't gonna monkey around for no bananas in return.

Why do I sound so spirited, yet arrogant, you might ask. It's because I care, and I want Element to make it.

**Comment by slavaww** [comment]
Yes, please! A button to initiate a simple voice call is absolutely necessary. It would be great to add an option in the settings to select call priority. Thanks!

**Comment by DEVXIX** [comment]
Pretty sure that's not happening so i just coded my own.

**Comment by Scaling6857** [comment]
@DEVXIX Would you mind sharing your code in a repo? Appreciate you.

**Comment by akarl10** [comment]
> Pretty sure that's not happening so i just coded my own.

I don't know what you exactly expect to be there in the addition what currently is present:
I have both on Element Web and Element X Anrdoi a voice call button (on one to one, else it's a video call, but I think this is implemented like that for every platform, like whatsapp, telegram, ...).
If I press this video is disabled by default and the remote party gets a "voice" call, that is if I answer on the phone, the video does not start and (with a ~ 1 sec delay I am in earpiece mode. Don't know if that is just visual or the runtime needs some moment, but in practice you press answer and put the phone to the ear, so it practically works as expected)

**Comment by schildbach** [comment]
For me, I have always to manually disable the video and the apps don't memorize that decision.

Also, screen space in a voice-only room could be put to better use, as there are no videos to show. So perhaps the chat could be put in the middle, rather than squished into the right sidebar.

**Comment by rwjack** [comment]
@schildbach did you update everything to latest? I used to have this issue but eventually the camera auto turn on issue was fixed and I do now have separate phone and video icons in EX IOS.

**Comment by schildbach** [comment]
> [@schildbach](https://github.com/schildbach) did you update everything to latest? I used to have this issue but eventually the camera auto turn on issue was fixed and I do now have separate phone and video icons in EX IOS.

Well, almost. My Element-Desktop Flatpak is still at 1.12.20 for some reason (latest is 1.12.21). Was it fixed in the most recent version?

**Comment by rwjack** [comment]
yeah, Element desktop is still showing only the video icon. Big F

**Comment by akarl10** [comment]
> yeah, Element desktop is still showing only the video icon. Big F

On my Element desktop there is definitely a phone icon in dm rooms. When I click I get the option to use Element Call or legacy call, like with video on dm. (I have not checked if the criteria is number of participants==2 or if the room must be marked as dm, in doubt with `/converttodm`, or both)

In rooms with more participants there is only video, but I think this is how it should be, mostly because in group calls you also get the "pre-join" configuration view, whereas on dm's the call/answer "joins" immediately.

Since this specific issue is closed as voice only calls are essentially implemented, I think if something does not work as expected or new ideas how the ui/ux should be a new issue should be created.
